# Generated by Django 6.0.4 on 2026-05-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('kot', 'KOT'), ('ready', 'Ready'), ('billed', 'Billed')], default='kot', max_length=20),
        ),
    ]
