# Generated by Django 6.0.3 on 2026-04-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
