# Generated by Django 6.0.3 on 2026-05-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image_url',
        ),
    ]
